name: "Bounty Proposal"
description: Have a suggestion for how to improve UbiquiBot? Let us know!
title: "Bounty Proposal:"

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request Form
        Thank you for taking the time to file a feature request! Please let us know what you're trying to do, and how UbiquiBot can help.

  - type: textarea
    attributes:
      label: Describe the background or context
      description: Please let us know what inspired you to write this proposal. Backlinking to specific comments is usually sufficient context.
    validations:
      required: false
  
  - type: textarea
    attributes:
      label: Describe the solution
      description: A clear description of what you want to happen. Add any considered drawbacks.
    validations:
      required: true
