name: Releases
on:
  create:
    tag:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      #

      - name: Checkout repository
        uses: actions/checkout@v3

      #

      - name: Authenticate as UbiquiBot
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.UBIQUITY_BOUNTY_BOT_APP_ID }}
          private_key: ${{ secrets.UBIQUITY_BOUNTY_BOT_PRIVATE_KEY }}

      #

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ steps.get_installation_token.outputs.token }}
